config/routes.rb
Resume::Application.routes.draw do

  resources :requests

  resources :comments

  resources :interviews

  resources :priorities

  resources :statuses

  resources :projects

  resources :users do
    collection do
      get :followings
    end
  end

  resources :candidates do
    collection do
      get :tag
    end
    get 'toggle_follow'
    resources :interviews do
      resources :comments
    end
    get 'mark_archive'
  end

  resources :hr, :bm, :administrator, :pl, :interviewer, :controller => "users"
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match "password_change" => "users#password_change", :as => "password_change"
  match 'get_interviews' => "interviews#get_interviews" , :as => :get_interviews
  match 'get_interviews/:interviewer_id' => "interviews#get_interviews" , :as => :get_interviews
  match 'interview/:view' => 'interviews#index'
  match 'interviews/move' => "interviews#move"
  match 'interviews/resize' => "interviews#resize"
  match "interviews/make_ical/:int_id" => "interviews#make_ical", :as => :make_ical

  match "interviews/:id/request/:status" => "interviews#status_change_request", :as => :interview_status_change
  match "interviews/:id/change_request" => "interviews#change_status_request"

  match 'create_custom_tags' => 'candidates#create_custom_tags'
  match 'pull_tags' => 'candidates#pull_tags'
  match 'fetch_candidates' => 'candidates#fetch_candidates', :as => 'fetch_candidates'
  match 'fetch_users/:assgined_id' => 'users#fetch_users', :as => 'fetch_users'
  match 'mark_archive_for_selected_candidates' => 'candidates#mark_archive_for_selected_candidates', :as => 'mark_archive_for_selected_candidates'
  match "my_trackings" => "candidates#my_trackings", :as => 'my_trackings'
  match "candidates/tag/:name" => "candidates#tag", :as => :tag_candidates, :constraints => { :name => /.+(?=\.(html|xml|js))|.+/ }
  match "add_candidate" => "candidates#new", :as => :add_candidate, :via => :get
  match "forgotten" => "sessions#forgotten", :as => :forgotten
  match "career" => "career#new", :as => :career, :via => :get
  match "career" => "career#create", :as => :career, :via => :post

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :interview
  belongs_to :candidate
  belongs_to :user

  attr_accessor :status_value
  after_save do |comment|
    comment.candidate.update_attribute(:status, comment.status_value) unless comment.status_value.blank?
    comment.interview.update_attribute(:status, comment.status_value) unless comment.status_value.blank?
    Notifier.delay.interview_feedback_mail(comment)
    Notifier.delay.interview_feedback_mail(comment, comment.interview.scheduler)
    followers = comment.candidate.user_followers
    followers.each do |user|
      Notifier.delay.interview_feedback_mail(comment, user)
    end
  end

  scope :filter_by_user, lambda { |user_id| where("user_id = ?", user_id) }


  def helpers
    ActionController::Base.helpers
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_candidate
  # GET /comments
  # GET /comments.json
  def index
    @interview = Interview.find(params[:interview_id])
    @comments = @interview.comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = current_user.comments.new
    @interview = Interview.find(params[:interview_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(params[:comment])
    @comment.status_value = FEEDBACK_STATUS.key(@comment.status)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to interviews_path, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    params[:comment][:status_value] = FEEDBACK_STATUS.key(params[:comment][:status])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to interviews_path, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to interviews_path }
      format.json { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.text_area :description %>
</div>
<%= f.hidden_field :interview_id, :value => params[:interview_id] %>
<%= f.hidden_field :candidate_id, :value => params[:candidate_id] %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<br />
<div class="field">
  <%= f.label :status %>:
  <%if @interview.user == current_user%>
  <% if @comment.status == 'Cancelled' %>
    <%='Cancelled' %>
  <%elsif @comment.status == 'Clear'%>
    <%='Clear'%>
  <% else %>
    <%= f.select(:status, FEEDBACK_STATUS, :selected => @comment.status) %>
  <% end %>
  <%else%>
    <b><%= @comment.status ? @comment.status : "Inprocess"%></b>
  <%end%>
</div>
<br />
<div class="actions">
  <%= f.submit %> <%= link_to "Back", :back, :class => 'back_link' %>
</div>
<div>
<script type="text/javascript"> 
$(function() {
  var my_inst = new TINY.editor.edit('editor',{
        id:'comment_description',
        width:584,
        height:175,
        cssclass:'te',
        controlclass:'tecontrol',
        rowclass:'teheader',
        dividerclass:'tedivider',
        controls:['bold','italic','underline','strikethrough','|','subscript','superscript','|',
                          'orderedlist','unorderedlist','|','outdent','indent','|','leftalign',
                          'centeralign','rightalign','blockjustify','|','unformat','|','undo','redo','n',
                          'font','size','style','|','hr','link','unlink','|','cut','copy','paste'],
        footer:true,
        fonts:['Verdana','Arial','Georgia','Trebuchet MS'],
        xhtml:true,
        cssfile:'/assets/style.css',
        bodyid:'editor',
//     footerclass:'tefooter',
//      toggle:{text:'source',activetext:'wysiwyg',cssclass:'toggle'},
//      resize:{cssclass:'resize'}
});
$('form').submit(function () {
editor.post();
});

});
</script>
</div>
<%end%>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<div>
<div id="create_event_dialog">
  <div id="create_event">
  </div>
</div>
  <h2></h2>
         <%@comments.each do |comment|%>
          <ul>
          <li><div><%=comment.description%></div>
          <span>commented by  <%=link_to comment.user.name, comment.user%> on <%=comment.created_at%> 
            </span>
      <span class="tags"></span>
      <div class="options">
        <%if comment.user == current_user%>
        <%=link_to 'Edit', edit_candidate_interview_comment_path(comment.candidate, comment.interview,comment)%> | 
        <%= link_to 'Destroy', candidate_interview_comment_path(comment.candidate, comment.interview,comment), confirm: 'Are you sure?', method: :delete %>
        <%end%>
      </div>
					</li>
				</ul>
  <%end%>
       <div >
        <%=link_to 'New Comment', new_candidate_interview_comment_path(Candidate.find(params[:candidate_id]), @interview)%>
      </div>
</div>

app/views/comments/new.html.erb
<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td width="75%"><h1>New Feedback ~ <%= @candidate.name %></h1></td>
  </tr>
</table>
<%= render '/interviews/candidate_info' %>

<table width="90%" cellpadding="5" cellspacing="5" border="0" style="border: 1px solid #ccc">
  <tr>
    <td width="50%"><strong>Schedule at: </strong><%= @interview.formated_scheduled_at %></td>
    <td width="50%"><strong>Reviewer: </strong><%= @interview.user.name %></td>
  </tr>
</table>
<p>&nbsp;</p>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @comment.description %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Interview:</b>
  <%= @comment.interview_id %>
</p>

<p>
  <b>Status:</b>
  <%= @comment.status %>
</p>

<p>
  <b>Candidate:</b>
  <%= @comment.candidate_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>