config/routes.rb
Resume::Application.routes.draw do

  resources :requests

  resources :comments

  resources :interviews

  resources :priorities

  resources :statuses

  resources :projects

  resources :users do
    collection do
      get :followings
    end
  end

  resources :candidates do
    collection do
      get :tag
    end
    get 'toggle_follow'
    resources :interviews do
      resources :comments
    end
    get 'mark_archive'
  end

  resources :hr, :bm, :administrator, :pl, :interviewer, :controller => "users"
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match "password_change" => "users#password_change", :as => "password_change"
  match 'get_interviews' => "interviews#get_interviews" , :as => :get_interviews
  match 'get_interviews/:interviewer_id' => "interviews#get_interviews" , :as => :get_interviews
  match 'interview/:view' => 'interviews#index'
  match 'interviews/move' => "interviews#move"
  match 'interviews/resize' => "interviews#resize"
  match "interviews/make_ical/:int_id" => "interviews#make_ical", :as => :make_ical

  match "interviews/:id/request/:status" => "interviews#status_change_request", :as => :interview_status_change
  match "interviews/:id/change_request" => "interviews#change_status_request"

  match 'create_custom_tags' => 'candidates#create_custom_tags'
  match 'pull_tags' => 'candidates#pull_tags'
  match 'fetch_candidates' => 'candidates#fetch_candidates', :as => 'fetch_candidates'
  match 'fetch_users/:assgined_id' => 'users#fetch_users', :as => 'fetch_users'
  match 'mark_archive_for_selected_candidates' => 'candidates#mark_archive_for_selected_candidates', :as => 'mark_archive_for_selected_candidates'
  match "my_trackings" => "candidates#my_trackings", :as => 'my_trackings'
  match "candidates/tag/:name" => "candidates#tag", :as => :tag_candidates, :constraints => { :name => /.+(?=\.(html|xml|js))|.+/ }
  match "add_candidate" => "candidates#new", :as => :add_candidate, :via => :get
  match "forgotten" => "sessions#forgotten", :as => :forgotten
  match "career" => "career#new", :as => :career, :via => :get
  match "career" => "career#create", :as => :career, :via => :post

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates
  has_many :interviews, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :candidates, :through => :interviews
  has_many :schedules, :foreign_key => "scheduler_id", :class_name => "Interview"
  has_many :interviewers, :class_name => "OtherInterviewer", :dependent => :destroy

  has_many :requests

  attr_accessible :name, :username, :type, :email, :password, :password_confirmation

  validates :name, :email, :presence => true
  validates :email, :username, :uniqueness => true
  validates :password, :password_confirmation, :presence => true, :on => :create
  validates :password, :confirmation => true
  validates :password, :length => { :minimum => 6 }, :allow_blank => true

  scope :interview_panel, where(:type => INTERVIEW_PANEL_USER_TYPES)
  scope :current_user, lambda { |user_id| where("id = ?", user_id) }

  acts_as_follower

  after_create do |user|
    Notifier.delay.user_welcome_mail(user, user.password)
  end

  def admin?
    false
  end
  
  def role
    USER_ROLES.key(self.type)
  end

  def self.inherited(child)
    child.instance_eval do
      def model_name
        User.model_name
      end
    end
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :except => [:new, :create]
  load_and_authorize_resource
  #before_filter :authenticate_admin
  # GET /users
  # GET /users.json
  def index
    @users = User.page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @interviews = @user.comments.order("updated_at DESC").limit(5)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  def password_change
    if request.put?
      @user = current_user
      if @user.update_attributes(params[:user]) && (not params[:user][:password].blank?)
        redirect_to :root, :notice => 'Password changed successfully.'
      elsif params[:user][:password].blank?
        redirect_to password_change_path, :notice => 'Password should not be blank.'
      end
    end
  end

  def fetch_users
    if params[:q]
    like_name = "%".concat(params[:q].concat("%"))
    users = User.where("id != ? and name like ?", params[:assgined_id].to_i, like_name).order("name")
    else
    users = User.all.order("name")
    users.delete_if {|x| x.id == params[:assigned_id]}
    end
    list = users.map {|u| Hash[ id: u.id, name: u.name, subject: u.role]}
    render json: list
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
  def interview_status_count(s)
    @user.comments.where(:status => s).count
  end
  
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_messages">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @user.errors.full_messages %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<table class="create_edit_form" cellpadding="5" cellspacing="5">
  <tbody>
    <tr>
      <td class="form_label"><%= f.label :name %></td>
      <td class="form_input"><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :username %></td>
      <td class="form_input"><%= f.text_field :username %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :email %></td>
      <td class="form_input"><%= f.text_field :email, :autocomplete => "off" %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :password %></td>
      <td class="form_input"><%= f.password_field :password, :autocomplete => "off" %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :password_confirmation %></td>
      <td class="form_input"><%= f.password_field :password_confirmation, :autocomplete => "off" %></td>
    </tr>
    <% if check_admin_or_hr(current_user.type) %>
    <tr>
      <td class="form_label"><%= f.label :type, "Role" %></td>
      <td class="form_input"><%= f.select(:type, USER_ROLES, :selected => @user.type) %></td>
    </tr>
    <% end %>
    <tr class="button">
      <td></td>
      <td class="form_input"><%= f.submit %> </td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/users/_settings.html.erb
<%if check_admin_or_hr(current_user.type.to_s)
  case params[:action]
    when 'password_change' %>
    <%= link_to( image_tag('manageusers.png', :title => 'Manage Users'), users_path, :class=>"top_link top_bar_elements") %>
      <%= link_to( image_tag('managetags.png', :title => 'Manage Tags'), create_custom_tags_path, :class=>"top_link top_bar_elements") %>
    <%  when 'my_trackings' %>
      <%= link_to( image_tag('manageusers.png', :title => 'Manage Users'), users_path, :class=>"top_link top_bar_elements") %>
      <%= link_to( image_tag('managetags.png', :title => 'Manage Tags' ), create_custom_tags_path, :class=>"top_link top_bar_elements") %>
    <%  when 'create_custom_tags' %>
      <%= link_to( image_tag('manageusers.png', :title => 'Manage Users'), users_path, :class=>"top_link top_bar_elements") %>
    <% else %>
      <%= link_to( image_tag('managetags.png', :title => 'Manage Tags'), create_custom_tags_path, :class=>"top_link top_bar_elements") %>
<% end %>
<% end %>
      <%= link_to( image_tag('interviews.png', :title => 'My Trackings'), my_trackings_path, :class=>"top_link top_bar_elements") unless params[:action] == 'my_trackings' %>
      <%= link_to( image_tag('settings.png', :title => 'Change Password'), password_change_path, :class=>"top_link top_bar_elements") unless params[:action] == 'password_change' %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/followings.html.erb
<%= render :partial => '/users/settings' %>
<%= render :partial => 'candidates_list' %>

app/views/users/index.html.erb
<%= render 'settings' %>
<div>
<h1>Users</h1>
    <div id="rows">
        <% @users.each do |user| %>
          <ul><li>
          <%= link_to user.name, user_path(user) %>
          <em><%= user.username %> | <%= user.email %></em>
          <span><%= user.role %></span>
          <div class="options"><%= link_to 'Show', user %> | <%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Destroy', user, confirm: 'Are you sure to delete the user?', method: :delete %></div>
          </li></ul>
        <% end %>
      </table>
    </div>
    <br />
    <div class="list_top_bar">
      <%= link_to 'New User', new_user_path %>
      <div id="pagination">
        <%= will_paginate(@users)%>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/password_change.html.erb
<%= render 'settings' %>
<h2>Change Password</h2>
<%= form_tag(password_change_path, :method => "put", :class => "change_password") do%>
<% if @user.try(:errors).try(:any?) %>
<div id="errorExplanation">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @user.errors.full_messages %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<table class="create_edit_form" cellpadding="5" cellspacing="5">
  <tbody>
    <tr>
      <td class="form_label">Password</td>
      <td class="form_input"> <%= password_field :user, :password %> </td>
    </tr>
    <tr>
      <td class="form_label"> Confirm Password </td>
      <td class="form_input"> <%= password_field :user, :password_confirmation %> </td>
    </tr>
    <tr class="button">
      <td></td>
      <td class="form_input"><%= submit_tag("Update") %></td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/users/show.html.erb
<style>
table{border:1px solid #ccc}
tr{border:1px solid #999;}
th{background-color:#555;color:#FFF}
td,th{border-right:1px solid #999; padding:10px 0 10px 10px;text-align:left;}
tbody tr:nth-child(odd) {background-color: #F2F2F2;}
</style>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>
  <b>Role:</b>
  <%= @user.role %>
</p>

<p><b>Quick Stats:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Clear:</b> (<%= interview_status_count('Clear') %>) &nbsp;|&nbsp; <b>Hold:</b> (<%= interview_status_count('Hold') %>)&nbsp; | &nbsp; <b>Drop:</b> (<%= interview_status_count('Drop') %>)</p>

<% unless @interviews.empty? %>
<hr />
<p><h3>Last 5 Interview Feedback(s)</h3></p>
<table width="100%" cellpadding="0" cellspacing="0" border="0">
	<tbody>
		<tr>
			<th width="40%">Candidate Name</th>
			<th>Interview Date</th>
			<th>Status</th>
		</tr>
	<%@interviews.each do |i| %>
	<tr>
		<td><%= link_to i.candidate.name, candidate_path(i.candidate) %></td>
		<td><%= i.interview.formated_scheduled_at %></td>
		<td><%= i.status%></td>
	</tr>
	<% end %>
	</tbody>
</table>

<% end %>
<p>&nbsp;</p>
<p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</p>