config/routes.rb
Resume::Application.routes.draw do

  resources :requests

  resources :comments

  resources :interviews

  resources :priorities

  resources :statuses

  resources :projects

  resources :users do
    collection do
      get :followings
    end
  end

  resources :candidates do
    collection do
      get :tag
    end
    get 'toggle_follow'
    resources :interviews do
      resources :comments
    end
    get 'mark_archive'
  end

  resources :hr, :bm, :administrator, :pl, :interviewer, :controller => "users"
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match "password_change" => "users#password_change", :as => "password_change"
  match 'get_interviews' => "interviews#get_interviews" , :as => :get_interviews
  match 'get_interviews/:interviewer_id' => "interviews#get_interviews" , :as => :get_interviews
  match 'interview/:view' => 'interviews#index'
  match 'interviews/move' => "interviews#move"
  match 'interviews/resize' => "interviews#resize"
  match "interviews/make_ical/:int_id" => "interviews#make_ical", :as => :make_ical

  match "interviews/:id/request/:status" => "interviews#status_change_request", :as => :interview_status_change
  match "interviews/:id/change_request" => "interviews#change_status_request"

  match 'create_custom_tags' => 'candidates#create_custom_tags'
  match 'pull_tags' => 'candidates#pull_tags'
  match 'fetch_candidates' => 'candidates#fetch_candidates', :as => 'fetch_candidates'
  match 'fetch_users/:assgined_id' => 'users#fetch_users', :as => 'fetch_users'
  match 'mark_archive_for_selected_candidates' => 'candidates#mark_archive_for_selected_candidates', :as => 'mark_archive_for_selected_candidates'
  match "my_trackings" => "candidates#my_trackings", :as => 'my_trackings'
  match "candidates/tag/:name" => "candidates#tag", :as => :tag_candidates, :constraints => { :name => /.+(?=\.(html|xml|js))|.+/ }
  match "add_candidate" => "candidates#new", :as => :add_candidate, :via => :get
  match "forgotten" => "sessions#forgotten", :as => :forgotten
  match "career" => "career#new", :as => :career, :via => :get
  match "career" => "career#create", :as => :career, :via => :post

  root :to => 'home#index'

end

app/views/shared/_top_menu.html.erb
<div id="top_right_bar">
  <%= link_to image_tag('home.png', :title => 'Home'), interviews_path, :class => "top_link top_bar_elements" %>
  <% if INTERVIEW_PANEL_USER_TYPES.include?(current_user.type.to_s) %>
    <%= link_to( image_tag('interviews.png', :title => 'Candidates'), candidates_path, :class=>"top_link top_bar_elements") %>
    <%= link_to( image_tag('calendar.png', :title => 'Manage Interviews by Calendar View'), interviews_path(:view => 'calendar'), :class=>"top_link top_bar_elements") %>
  <% end %>
  <%= link_to( image_tag('settings.png', :title => 'Settings'), password_change_path, :class=>"top_link top_bar_elements") %>
  <div style="float:right"><%= link_to( image_tag('onoff.png', :title => 'Logout'), log_out_path, :confirm => "Are you sure to logout?", :class=>"top_link top_bar_elements") %></div><div style="clear:both; float:right"><%= current_user.name.capitalize %></div>
</div>