config/routes.rb
Resume::Application.routes.draw do

  resources :requests

  resources :comments

  resources :interviews

  resources :priorities

  resources :statuses

  resources :projects

  resources :users do
    collection do
      get :followings
    end
  end

  resources :candidates do
    collection do
      get :tag
    end
    get 'toggle_follow'
    resources :interviews do
      resources :comments
    end
    get 'mark_archive'
  end

  resources :hr, :bm, :administrator, :pl, :interviewer, :controller => "users"
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match "password_change" => "users#password_change", :as => "password_change"
  match 'get_interviews' => "interviews#get_interviews" , :as => :get_interviews
  match 'get_interviews/:interviewer_id' => "interviews#get_interviews" , :as => :get_interviews
  match 'interview/:view' => 'interviews#index'
  match 'interviews/move' => "interviews#move"
  match 'interviews/resize' => "interviews#resize"
  match "interviews/make_ical/:int_id" => "interviews#make_ical", :as => :make_ical

  match "interviews/:id/request/:status" => "interviews#status_change_request", :as => :interview_status_change
  match "interviews/:id/change_request" => "interviews#change_status_request"

  match 'create_custom_tags' => 'candidates#create_custom_tags'
  match 'pull_tags' => 'candidates#pull_tags'
  match 'fetch_candidates' => 'candidates#fetch_candidates', :as => 'fetch_candidates'
  match 'fetch_users/:assgined_id' => 'users#fetch_users', :as => 'fetch_users'
  match 'mark_archive_for_selected_candidates' => 'candidates#mark_archive_for_selected_candidates', :as => 'mark_archive_for_selected_candidates'
  match "my_trackings" => "candidates#my_trackings", :as => 'my_trackings'
  match "candidates/tag/:name" => "candidates#tag", :as => :tag_candidates, :constraints => { :name => /.+(?=\.(html|xml|js))|.+/ }
  match "add_candidate" => "candidates#new", :as => :add_candidate, :via => :get
  match "forgotten" => "sessions#forgotten", :as => :forgotten
  match "career" => "career#new", :as => :career, :via => :get
  match "career" => "career#create", :as => :career, :via => :post

  root :to => 'home#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  include UserInfo

  # before_destroy should be on top of associations, to get the assoicated objects of it, since we mentioned dependent as destroy.
  before_destroy do |candidate|
    candidate.interviews.upcoming.each do |interview|
      Notifier.delay.candidate_profile_delete_mail(candidate.name, interview.user, current_user, interview.formated_scheduled_at)
    end
    followers = candidate.user_followers
    followers.each do |user|
      Notifier.delay.candidate_profile_delete_mail(candidate.name, user, current_user, nil)
      user.stop_following(candidate)
    end
  end

  after_update do |candidate|
    followers = candidate.user_followers
    changes = candidate.changes.delete_if {|key, value| ["status", "updated_at"].include?(key)}
    if changes.length > 0
      followers.each do |user|
        Notifier.delay.candidate_profile_update_mail(candidate, user, current_user, changes)
      end
    end
  end

  acts_as_taggable_on :tags
  acts_as_followable

  has_attached_file :resume, :content_type => 'image/jpeg', :storage => :s3,
     :s3_credentials => "#{Rails.root}/config/s3.yml",
     :path => "/:style/:id/:filename"
  validates_attachment_presence :resume
  validates_attachment_content_type :resume, :content_type => [ 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', "application/rtf"], :message => 'invalid file format'
  validates_attachment_size :resume, :less_than => 2.megabytes
  validates :name, :presence => true

  has_many :interviews, :dependent => :destroy
  has_many :users, :through => :interviews

  scope :active, where("status !=  'Archive' or status is null")

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # GET /candidates
  # GET /candidates.json
  before_filter :authenticate, :except => [:new, :create, :pull_tags]
  load_and_authorize_resource
  skip_authorize_resource :only => [:new, :create, :pull_tags, :tag, :fetch_candidates, :toggle_follow, :my_trackings]

  def index
    if !params[:search].blank?
      @candidates = Candidate.tagged_with(params[:search], :any => true).page(params[:page])
      search_params = params[:search].index(',').nil? ? params[:search] : params[:search].split(',')
      @search_tags = ActsAsTaggableOn::Tag.named(search_params)
      search_params = search_params.join(', ') if search_params.kind_of?(Array)
      @title = "tagged with #{search_params}"
    elsif !params[:status].blank? && params[:status] != 'All'
      @candidates = Candidate.page(params[:page]).find_all_by_status(params[:status])
      @title = " on #{params[:status]} Status"
    else
      @candidates = Candidate.active.order("name").page(params[:page])
    end
    @tags = Candidate.tag_counts_on(:tags)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  def tag
    if request.delete?
      Candidate.tagged_with(params[:name]).each { |c| c.tag_list.remove(params[:name]) }
      ActsAsTaggableOn::Tag.delete(params[:tag_id])
      flash.notice = "Tag and its associated taggings are sucessfully deleted."
      redirect_to create_custom_tags_path
    else
#      @candidates = current_user.type.to_s == 'Interviewer' ? current_user.candidates.select("distinct(candidates.id), candidates.*").tagged_with(params[:name]).page(params[:page]) : Candidate.tagged_with(params[:name]).page(params[:page])
      @candidates = Candidate.tagged_with(params[:name]).page(params[:page])
      @title = "tagged with #{params[:name]}"
      @tags = Candidate.tag_counts_on(:tags)
      render :action => 'index'
    end
  end


  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new
    @tags = Candidate.tag_counts_on(:tags)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  def new_from_career_form
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])
    @tags = Candidate.tag_counts_on(:tags)

    respond_to do |format|
      if @candidate.save
        unless current_user.blank?
          format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
          format.json { render json: @candidate, status: :created, location: @candidate }
        else
          format.html { redirect_to add_candidate_path, notice: 'Candidate was successfully created.' }
          format.json { render json: add_path, status: :created }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to_back(candidates_url) }
      format.json { head :ok }
    end
  end

  # toggle_follow should rename as toggle_track
  def toggle_follow
    candidate = Candidate.find(params[:candidate_id])
    if current_user.following?(candidate)
      current_user.stop_following(candidate)
      render text: "Track"
    else
      current_user.follow(candidate)
      render text: "Untrack"
    end
  end

  def my_trackings
    follows = current_user.follows_by_type('Candidate')
    @candidates = follows.blank? ? [] : Candidate.where("id in (#{follows.map(&:followable_id).join(',')})").page(params[:page])
    @tags = Candidate.tag_counts_on(:tags)
  end

  def mark_archive
    @candidate = Candidate.find(params[:candidate_id])
    str_archive = (@candidate.status == "Archive") ? nil : "Archive"
    @candidate.update_attribute(:status, str_archive)
    redirect_to candidates_url
  end

  def fetch_candidates
    if params[:q]
    like= "%".concat(params[:q].concat("%"))
    candidates = Candidate.where("name like ?", like).order("name")
    else
    candidates = Candidate.all.order("name")
    end
    list = candidates.map {|c| Hash[ id: c.id, name: c.name, subject: (c.subject ? c.subject : "")]}
    render json: list
  end

  def mark_archive_for_selected_candidates
    candidates = Candidate.find_all_by_id(params[:select].values) unless params[:select].blank? && params[:changed_staus].blank?
    unless candidates.blank?
      candidates.each do |candidate|
        candidate.update_attribute(:status, params[:changed_status])
      end
    redirect_to candidates_url, :notice => 'Status was successfully updated.'
    else
    redirect_to candidates_url, :notice => 'No candidates selected for update.'
    end
  end

  def create_custom_tags
    tag_name = params[:name]
    if tag_name
      @tag = ActsAsTaggableOn::Tag.create(:name => tag_name.downcase)
      flash.now.notice = "Custom Tag Created Successfully"
    end
    @tag_list = ActsAsTaggableOn::Tag.all
  end

  def pull_tags
    render json: ActsAsTaggableOn::Tag.where("name LIKE ?", "%#{params[:q]}%")
  end

  def redirect_to_back(default = root_url)
    if !request.env["HTTP_REFERER"].blank? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to default
    end
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_candidates_list.html.erb
<div>
<% unless params[:action] == 'my_trackings' %>
  <%= render 'search_tags' %>
  <h1>Candidates</h1>
<% else %>
  <h1>My Tracking Candidates</h1>
<% end %>
    <div id="rows">
  <%#= form_tag(mark_archive_for_selected_candidates_path,:id => "modify_status") do%>
    <% unless @candidates.blank? %>
    <% @candidates.each do |candidate| %>
      <ul><li><%= link_to candidate.name, candidate_path(candidate), :class => "title" %>
      <em><%= candidate.subject%></em>
      <span><%= show_candidate_interview_details(candidate).html_safe %></span>
      <span class="tags"><%= show_tags(candidate).join(" ").html_safe unless candidate.tags.empty? %></span>
      <div class="options"><%= cta_links(:candidate, candidate) %></div>
      </li></ul>
  <% end %>
    <input type="hidden" id="changed_status" name="changed_status" />
  <%else%>
    <ul><li class="no_records_found">No candidates found.</li></ul>
  <%end%>
  <%#end%>
  </div>
<br />
<div class="list_top_bar">
  <div style="float:left">
<%= link_to 'New Candidate', new_candidate_path if can? :create, Candidate %>
  </div>
  <div id="pagination">
        <%= will_paginate(@candidates) unless @candidates.blank? %>
      </div>
    </div>
    <br />
<script type="text/javascript">
  $(document).ready(function() {
    //Script for filtering the candidates by status
    $("#status").change(function() {
      if($("#status").val() == "")
        alert("Please select a valid filter.")
      else
        $('#filter_candidate_by_status').submit();
    });
    //Script for select all
    $("#select_all").click(function() {
      if($('#select_all').is(':checked')) {
        $(".select_candidate").prop('checked', true);
      } else {
        $(".select_candidate").prop('checked', false);
      }
    });
    //Script for changing the status of the selected candidates
    $("#change_status").change(function() {
      if($(".select_candidate:checked").length == 0) {
        alert("Please select atleast one candidate.");
      } else if($("#change_status").val() == "") {
        alert("Please select a valid status.");
        } else {
        $("#changed_status").val($("#change_status").val());
        $("form#modify_status").submit();
      }
    });
  });

</script>

app/views/candidates/_form.html.erb
<%= form_for(@candidate, :html => { :multipart => true }) do |f| %>
<% if @candidate.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>
  <ul>
    <% @candidate.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<table class="create_edit_form" cellpadding="5" cellspacing="5">
  <tbody>
    <tr>
      <td class="form_label"><%= f.label :name %><sup>*</sup></td>
      <td class="form_input"><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :email, "Email Address" %></td>
      <td class="form_input"><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :mobile, "Mobile Number" %></td>
      <td class="form_input"><%= f.text_field :mobile %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :phone, "Landline Number" %></td>
      <td class="form_input"><%= f.text_field :phone %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :subject %></td>
      <td class="form_input"><%= f.text_field :subject %></td>
    </tr>
    <tr>
      <td class="form_label"><%= f.label :resume%><sup>*</sup></td>
      <td class="form_input"><%= f.file_field :resume, :class => "no_border" %><td>
        <%= show_resume(@candidate) unless @candidate.resume.blank?%>
    </tr>
    <tr>
      <td class="form_label">Tag List (upto 10 Tags)</td>
      <td class="form_input">
        <%= f.text_field :tag_list, :data => {:pre => @candidate.tags.map(&:attributes).to_json}, :id => "tag_autocomplete", :size => "20"  %>
      </td>
    </tr>
    <tr class="button">
      <td></td>
      <td class="form_input"><%= f.submit "Submit", :class => "small-width" %></td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/candidates/_search_tags.html.erb
<table>
  <tr>
    <td>
      <form class="searchform" id="searchform">
      <input type="text" name="search" id="tag_autocomplete" class="searchfield" value="<%= params[:search] %>" title="Search by Tags" data-pre="<%= @search_tags.map(&:attributes).to_json unless @search_tags.blank?  %>" />
      <input class="searchbutton hide" type="submit" value="Go" />
    </form></td>
    <!--
    <td width="45%">
      <form id="filter_candidate_by_status">
        <%#= select_tag('status', options_from_collection_for_select({"All" => "All"}.merge(FEEDBACK_STATUS).merge(HIRING_STATUS), :first, :last, params[:status]), {:prompt => "Filter Candidate By"}) %>
        <%#= select_tag("change_status", options_from_collection_for_select(HIRING_STATUS, :first, :last), {:prompt => "Mark as"}) if can? :update, Candidate %>
      </form>
    </td>
    -->
  </tr>
</table>
<div class="tagClound">
<% tag_cloud(@tags, %w(tag_cloud1 tag_cloud2 tag_cloud3 tag_cloud4)) do |tag, css_class| %>
  <%= link_to tag.name, tag_candidates_path(tag.name), :class => css_class %>
<% end %>
</div>

app/views/candidates/create_custom_tags.html.erb
<%= render 'users/settings' %>
<div>
  <h2> Create Technologies as Tag </h2>
  <% if !@tag.nil? && @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this  from being saved:</h2>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
        <li>
          <%= msg.sub("Name", "Tag Name") %>
        </li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_tag do %>
  <%= text_field_tag "name", nil, :id=>"tag_name", :onkeypress => "return alpha(event)" %>
<%= submit_tag "Create Tag" %>
<% end %>
</div>
<div>
  <h2> List of Technologies as Tag </h2>
  <%= @tag_list.map { |tag| "<span class='del'>" + (link_to tag.name, tag_candidates_path(tag.name)) + (link_to "[X]", nil, :class => "del hide", :id => tag.id, :name => tag.name, :confirm => "Are you sure to delete the tag?") + "</span>" }.join(", ").html_safe %>
</div>
<script>
function alpha(e) {
    var k;
    document.all ? k = e.keyCode : k = e.which;
    return ((k > 64 && k < 91) || (k > 96 && k < 123) || k == 8 || k == 32 || k == 45 || k == 46 || (k >= 48 && k <= 57) || k == 95);
}

  $(function() {
    $('a.del')
      .click(function() {
        jQuery.ajax({
            data: 'tag_id=' + this.id,
            dataType: 'script',
            type: 'delete',
            url: "/candidates/tag/"+this.name
          });
    });
    $('span.del').hover(
    function() {
      $(this).find('a.del').show();
    },
    function() {
      $(this).find('a.del').hide();
    }
  );
});
</script>

app/views/candidates/edit.html.erb
<h1>Edit Candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<%= render :partial => 'candidates_list' %>

app/views/candidates/my_trackings.html.erb
<%= render :partial => '/users/settings' %>
<%= render :partial => 'candidates_list' %>

app/views/candidates/new.html.erb
<h1>Add Candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path unless current_user.blank? %>

app/views/candidates/show.html.erb
<h1>Candidate <!--~ <%= @candidate.name %>--></h1>
<%= render '/interviews/candidate_info' %>
<%= render :partial => '/interviews/feed_back_info', :object => @candidate.interviews.uncancelled %>
<%= render :partial => '/interviews/upcoming', :object => @candidate.interviews.upcoming %>
<%= render '/interviews/previous_schedules' %>

<br />
<% if can?(:update, Candidate) %>
<%= link_to 'Edit', edit_candidate_path(@candidate)  %> |
<%= link_to 'Add an Interview Schedule', new_candidate_interview_path(@candidate) %> |
<% end %>
<br />